Portafolio 2.0/portafolio/aplicacion/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

app_name = "cliente_app"

urlpatterns = [

    #incio index--------------------------------------------------
    path(
        '',
         views.InicioView.as_view(),
         name='index'), 
    #logeandose----------------------------------------------------
    path(
        'login/',
         views.LoginUser.as_view(),
         name='logeo'
          ), 
    path(
        'register/',
         views.UserRegisterView.as_view(),
         name='register'
          ), 
    path(
        'logout',
         views.LogoutView.as_view(),
         name='logout'
          ),
    path(
        'verification/<pk>/',
         views.CodeVerificationView.as_view(),
         name='verification-user'
          ),
    path(
        'update',
         views.UpdatePasswordView.as_view(),
         name='update'
          ),
    path(
        'cliente/',
         views.ListCliente.as_view(),
          name='cliente'
          ),
    path(
        'resultado',
         views.resultado ,
          name='resultado'
          ), 
    path(
        'perfil/',
         views.ListPerfil.as_view(),
         name='perfil'), 
    path(
        'inicio/',
         views.InicioclienteView.as_view(),
         name='inicio'), 
          #logeandose terminandose----------------------------------------------------
    path(
        'reserva/',
         views.CrearReservaView.as_view(),
         name='reservando'), 
    path(
        'contacto/',
         views.ContactCreateView.as_view(),
         name='addcontacto'), 
          #Funcionario----------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'funcionario/',
         views.FuncionarioView.as_view()
         ), 
    path(
        'perfil_funcionario/',
         views.PerfilFuncionarioView.as_view(),
         name='perfil_funcionario'
         ), 
    path(
        'listareservafuncionario/<pk>/',
         views.ListReservaFuncionarioPdf.as_view(),
         name='listareservafuncionario'
         ),
    path(
        'actualizarcheck/<pk>/',
         views.ReservaFuncionarioUpdateView.as_view(),
         name='actualizarcheck'
         ), 
    path(
        'crear_listado/',
         views.CrearlistadoView.as_view()
         ), 
        #Mantener Cliente-------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_cliente/',
         views.MantenerClienteView.as_view(),
         name='mantener_cliente'
         ), 
    path(
        'actualizaruser/<pk>/',
         views.ClienteUpdateView.as_view(),
         name='actualizaruser'
         ), 
     path(
         'deleteuser/<pk>/',
         views.UsuarioDeleteView.as_view(),
         name='deleteuser'
        ), 
        #Mantener Departamento-------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_departamento/',
         views.MantenerDepartamentoView.as_view(),
         name='mantener_departamento'
         ), 
    path(
        'deletedepartamento/<pk>/',
         views.DepartamentoDeleteView.as_view(),
         name='deletedepartamento'
         ),
    path(
        'actualizardepartamento/<pk>/',
         views.DepartamentoUpdateView.as_view(),
         name='actualizardepartamento'
         ), 
    path(
        'ciudad/',
         views.CiudadView.as_view(),
         name='ciudad'
         ),
    path(
        'comuna/',
         views.ComunaView.as_view(),
         name='comuna'
         ),
    path(
        'inventario/',
         views.InventarioView.as_view(),
         name='inventario'
         ),
    path(
        'deleteinventario/<pk>/',
         views.InventarioDeleteView.as_view(),
         name='deleteinventario'
         ),
        #Mantener Reservas-------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_reserva/',
         views.MantenerReservaView.as_view(),
         name='mantener_reserva'
         ),
    path(
        'actualizarreserva/<pk>/',
         views.ActualizarReservaUpdateView.as_view(),
         name='actualizarreserva'
         ),
    path(
        'deletereserva/<pk>/',
         views.ReservaAdminDeleteView.as_view(),
         name='deletereserva'
         ), 
    path(
        'detailreserva/<pk>/',
         views.ReservaDetailView.as_view(),
         name='detailreserva'
         ), 
        #Mantener Servicios--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_servicio/',
         views.MantenerServicioView.as_view(),
         name='mantener_servicio'
         ),
    path(
        'actualizarservicio/<pk>/',
         views.ServicioUpdateView.as_view(),
         name='actualizarservicio'
         ),
    path(
        'deleteservicio/<pk>/',
         views.ServicioAdminDeleteView.as_view(),
         name='deleteservicio'
         ), 
        #Mantener Tour--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_tour/',
         views.TourView.as_view(),
         name='mantener_tour'
         ),
    path(
        'actualizartour/<pk>/',
         views.TourUpdateView.as_view(),
         name='actualizartour'
         ),
    path(
        'deletetour/<pk>/',
         views.TourDeleteView.as_view(),
         name='deletetour'
         ), 
        #Mantener Conductor--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_conductor/',
         views.ConductorView.as_view(),
         name='mantener_conductor'
         ),
    path(
        'actualizarconductor/<pk>/',
         views.ConductorUpdateView.as_view(),
         name='actualizarconductor'
         ),
    path(
        'deleteconductor/<pk>/',
         views.ConductorDeleteView.as_view(),
         name='deleteconductor'
         ), 
        #Mantener Vehiculo--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'mantener_vehiculo/',
         views.VehiculoView.as_view(),
         name='mantener_vehiculo'
         ),
    path(
        'actualizarvehiculo/<pk>/',
         views.VehiculoUpdateView.as_view(),
         name='actualizarvehiculo'
         ),
    path(
        'deletevehiculo/<pk>/',
         views.VehiculoDeleteView.as_view(),
         name='deletevehiculo'
         ), 
        #Mantener Multa--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'multa/',
         views.MultaView.as_view(),
         name='multa'
         ),
    path(
        'actualizarmulta/<pk>/',
         views.MultaUpdateView.as_view(),
         name='actualizarmulta'
         ),
    path(
        'deletemulta/<pk>/',
         views.MultaDeleteView.as_view(),
         name='deletemulta'
         ), 
        #Perfil Administrador--------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'perfiladministrador/',
         views.PerfilAdminListView.as_view(),
         name='perfiladministrador'
         ),
    path(
        'actualizar_perfil/<pk>/',
         views.PerfilUpdateView.as_view(),
         name='actualizar_perfil'
         ),

        #probando venta--------------------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'reservando/',
         views.AgregarReservaView.as_view(),
         name='reservando'
         ),
        #Pago--------------------------------------------------------------------------------------------------------------------------------------------------------------
    path(
        'informepdf/',
         views.ListReservaListView.as_view(),
         name='informepdf'), 
    path(
        'lista-reserva/<pk>/',
         views.ListReservaPdf.as_view(),
         name='reserva_all'
         ), 
    path(
        'pagos_adm/',
         views.PagosView.as_view()
         ), 
    path(
        'lista_acompañante/',
         views.ListAcompañante.as_view(),
          name='listadoacompañante'), 
    path(
        'registroacom/',
         views.CrearAcompañanteView.as_view(),
          name='registroacom'
          ), 
     path(
         'editacom/<pk>/',
          views.AcompañanteUpdateView.as_view(),
           name='editacom'
           ), 
     path(
         'deleteacomp/<pk>/',
          views.AcompañanteDelete.as_view(),
           name='deleteacomp'
           ), 
     path(
         'cancelarreserva/<pk>/',
          views.ReservaDelete.as_view(),
           name='cancelarreserva'
           ), 
     path(
        'mantener_servicios/',
         views.ServiciosView.as_view(),
          name='mantener_servicios'
          ), 
     path(
        'generar_estadistica/',
         views.EstadisticaView.as_view(),
          name='generar_estadistica'
          ), 
     path(
        'generar_informe/',
         views.InformeView.as_view(),
          name='generar_informe'
          ),
     path(
        'reservando-update/<pk>/',
         views.ActualizarReservaView.as_view(),
          name='reservando-update'
          ),
     path(

Portafolio 2.0/portafolio/portafolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from aplicacion import views
from django.urls import reverse_lazy
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('aplicacion.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portafolio 2.0/portafolio/aplicacion/templates/Cliente.html
{% extends "cliente_generic.html" %}
{% load static %}

{% block content %}

{% if reservita %}

<div class="listadoreserva">
<div class="container">
    <h1>Listado de Reservas</h1>
    <div style="height:50px"></div>
    <p class="lead">
    <p>Aqui podra encontrar a todas tus reservas hechas a lo largo del tiempo</p>
    <hr>
    <input class="form-control col-md-3 light-table-filter" data-table="order-table" type="text" placeholder="Buscador..">
    <br>
    <br>
    <table class="table table-bordered order-table ">
      <thead>
      <div class="nombrestr">
        <tr>
          <th>Departamento</th>
          <th>Cantidad Dias</th>
          <th>Fecha llegado</th>
          <th>Fecha Termino</th>
          <th>Codigo Reserva</th>
          <th>Estado</th>
          <th>Cancelar</th>
          <th>Voucher</th>
        </tr>
      </thead>
    </div>
    {% for reservita in reservita %}
      <tr>
        <td>{{ reservita.departamento}}</td>
        <td>{{ reservita.count}}</td>
        <td>{{ reservita.Fecha_Reserva_Inicios}}</td>
        <td>{{ reservita.Fecha_Reserva_Terminos}}</td>
        <td>{{ reservita.Codigo_Reservas}}</td>
        {% if reservita.Estado_Reservas is False %}
        <td>Check</td>
        {% endif %}
        <td><a href="/cancelarreserva/{{ reservita.id }}">
            Cancerlar
        </a></td>
        <td><a href="{% url 'cliente_app:reserva_all' reservita.id %} " target="_blank">Voucher</a></td>

    </tr>
      </tr>
    {% endfor %}
    </table>
    <p>Si desea registrar una Reserva haga click en el siguiente link <a href="">Haga click aqui para Reserva</a></p>
    </div>
</div>
{% else %}
<div id="resultadolisto">
  <br> <br> <br> 
  <h2>No hay registros de Reservas, favor añadir</h2>
  <br> <br> 
  </div>
{% endif %}


{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/actualizarreserva.html
{% extends "cliente_generic.html" %}

{% load static %}



{% block content %}
<br>  
<div class="reserva-arriendo">
 <div class="contenedor">
     <form action="" class="form" method="POST">
     <div class="form-header">
         <h1 class="form-title"><i class="fas fa-plus-circle"></i>Actualizar<span> Reserva </span></h1>
     </div> 
     <div class="texto-reserva">
         <p>Actualizar Reserva
         </p>
     </div>
           <label>Fecha de Ingreso</label><br>
           {{ form.Fecha_Reserva_Inicio }}<hr><br>
           <label>Fecha de Salida</label><br>
           {{ form.Fecha_Reserva_Termino }}<hr><br>
           <label>Departamento a Elegir</label><br>
           {{ form.departamento }}<hr><br>
           <label>Cantidad de dias</label><br>
           {{ form.Cantidad_Dias }}<hr><br>
           <label>Servicios Extras</label><br>
           {{ form.servicioextra }}<hr><br>  
           <label>Usuario</label><br>   
           {{ form.user }}<hr><br>       
              <br><br>
              {% csrf_token %}
              <input type="submit" class="form-submit" value="Actualizar" onClick="verificarCasilla(this.form)">
              <input type="reset" class="form-submit" value="Limpiar Formulario">
              <a href="/inicio">Volver al Menu</a>
              </form>
          </div>
      </div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/actualizarvehiculo.html
{% extends "cliente_generic.html" %}

{% load static %}



{% block content %}

<br>  
<div class="reserva-arriendo">
 <div class="contenedor">
     <form action="" class="form" method="POST">
     <div class="form-header">
         <h1 class="form-title">Modificar<span> Vehiculo</span></h1>
     </div> 
     <div class="texto-reserva">
         <p>Aqui podras modificar al Vehiculo
         </p>
     </div>
              <label>Patente</label><br>
              {{ form.patente }}<br><br><br>

              <label>Color del Vehiculo(Primario)</label><br>
              {{ form.color_vehiculo }}<br><br><br>

              <label>Cantidad de Puertas</label><br>
              {{ form.cant_puerta}}<br><br><br>

              <label>Aire Acondicionado</label><br>
              {{ form.aire_acondicionado }}<br><br><br>

              <label>Cantidad de Asientos</label><br>
              {{ form.cant_asiento }}<br><br><br>  

              <label>Disponibilidad</label><br>   
              {{ form.disponibilidad_vehi }}<br><br><br>    
  
              <label>Imagen del Vehiculo</label><br>   
              {{ form.imagen_vehiculo }}<br><br><br>   

              <label>Modelo</label><br>   
              {{ form.modelo }}<br><br><br>   

              <label>Marca</label><br>   
              {{ form.marca }}<br><br><br>  
              <br><br>
              {% csrf_token %}
              <input type="submit" class="form-submit" value="Modificar" onClick="verificarCasilla(this.form)">
              <input type="reset" class="form-submit" value="Limpiar Formulario">
    </form>
 </div>
</div>

{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/deleteconductor.html
{% extends "cliente_generic.html" %}
{% load static %}


{% block content %}
<div class="reserva-arriendo">
  <div class="contenedor">
      <form action="" class="form" method="POST">
      <div class="form-header">
          <h1 class="form-title"><i class="fas fa-plus-circle"></i>Eliminar <span> Conductor </span></h1>
      </div> 
      <br><br><br><br>
      {% csrf_token %}
      <p>confirme que desea eliminar conductor</p>
      <br><br><br>
      <input class="btn btn-lg btn-primary btn-block" type="submit" value="Eliminar">
      </form>
  </div>
</div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/deletetour.html
{% extends "cliente_generic.html" %}
{% load static %}


{% block content %}
<div class="reserva-arriendo">
  <div class="contenedor">
      <form action="" class="form" method="POST">
      <div class="form-header">
          <h1 class="form-title"><i class="fas fa-plus-circle"></i>Eliminar <span> Tour </span></h1>
      </div> 
      <br><br><br><br>
      {% csrf_token %}
      <p>confirme que desea eliminar tour</p>
      <br><br><br>
      <input class="btn btn-lg btn-primary btn-block" type="submit" value="Eliminar">
      </form>
  </div>
</div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/editacom.html
{% extends "cliente_generic.html" %}
{% load static %}


{% block content %}
<div class="reserva-arriendo">
  <div class="contenedor">
      <form action="" class="form" method="POST">
      <div class="form-header">
          <h1 class="form-title"><i class="fas fa-plus-circle"></i>Modificar <span> Acompañante </span></h1>
      </div> 
      <div class="texto-reserva">
          <p>Modificar a su acompañante.
          </p>
      </div>
            <label>Rut</label><br>
            {{ form.acom_rut }}<br><br>
            <label>Nombre/s</label><br>
            {{ form.acom_nombre }}<br><br> 
            <label>Apellido/s</label><br>
            {{ form.acom_apellidos }}<br><br> 
            <label>Edad</label><br>
            {{ form.acom_edad }}<br><br> 
            <label>Nacionalidad</label><br>
            {{ form.acom_nacionalidad }}<br><br> 
            <label>Correo Electronico</label><br>   
            {{ form.acom_email }}<br><br> 
            <label>Telefono</label><br>
            {{ form.acom_telefono }}<br><br> 
               {% csrf_token %}
               <input class="btn btn-lg btn-primary btn-block" type="submit" value="Modificar">
               <input class="btn btn-lg btn-primary btn-block" type="reset" value="Limpiar Formulario"><br> 
               <p class="m-b-0 m-t">¿Ir al menu? <a href="/inicio">Haga Click Aqui</a>.</p>
             </form>
           </div>
       </div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/funcionario.html
{% extends "funcionario_generic.html" %}
{% load static %}

{% block content %}

<div class="listadoreserva">
    <div class="container">
        <h1>Bienvenido</h1>
        <div style="height:50px"></div>
        <p class="lead">
        <p>Listado de reservas</p>
        <hr>
        <p></p>
        <input class="form-control col-md-3 light-table-filter" data-table="order-table" type="text" placeholder="Buscador..">
        <br>
        <br>
        <table class="table table-bordered order-table ">
          <thead>
          <div class="nombrestr">
            <tr>
              <th>Codigo</th>
              <th>Nombre</th>
              <th>Departamento</th>
              <th>Fecha</th>
              <th>Servicios</th>
              <th>Pago pendiente</th>
              <th>Estado</th>
              <th>Check in</th>
              <th>Check out</th>
            </tr>
          </thead>
        </div>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><center><button>Listado</button></center></td>
            <td><center><button>Listado</button></center></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><center><button>Listado</button></center></td>
            <td><center><button>Listado</button></center></td>
          </tr>
        </table>
        <p>Si desea registrar un listado haga click en el siguiente link <a href="#"> Realizar un listado</a></p>
        </div>
    </div>


{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/inventario.html
{% extends "cliente_generic.html" %}
{% load static %}

{% block content %}

<div class="listadoreserva">
    <div class="container">
        <h1>Inventario</h1>
        <br>
        <table class="table table-bordered order-table ">
          <thead>
          <div class="nombrestr">
            <tr>
              <th>Identificador</th>
              <th>Reparacion</th>
              <th>Mejoramiento</th>
              <th>Eliminar</th>
            </tr>
          </thead>
        </div>
          <tr>
            {% for inventario in inventario %}
            <td>{{ inventario.id}}</td>
            <td>{{ inventario.reparacion}}</td>
            <td>{{ inventario.mejoramiento}}</td>
            <td><a href="/deleteinventario/{{ inventario.id }}" 
                onClick="return confirm('¿Seguro que quieres eliminarel inventario?');">
                    Borrar
            </a></td>
           </tr>
          {% endfor %}
        </table>
        </div>
    </div>
</div>
<div class="reserva-arriendo">
    <div class="contenedor">
        <form action="" class="form" method="POST">
        <div class="form-header">
            <h1 class="form-title">Crear<span> Inventario</span></h1>
        </div> 
        <div class="texto-reserva">
            </p>
        </div>
              <label>Reparacion</label><br>
              {{ form.reparacion }}<hr><br>
              <label>Mejoramiento</label><br>
              {{ form.mejoramiento }}<hr><br>
                 <br><br>
                 {% csrf_token %}
                 <input type="submit" class="form-submit" value="Añadir" onClick="verificarCasilla(this.form)">
                 <a href="/mantener_departamento">Volver al Menu</a>
                 </form>
            </div>
     </div>
</div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/pagos_adm.html
{% extends "cliente_generic.html" %}
{% load static %}

{% block content %}
<br>  
<div class="reserva-arriendo">
 <div class="contenedor">
     <form action="" class="form" method="POST">
     <div class="form-header">
         <h1 class="form-title">Hacer<span> Pagos</span></h1>
     </div> 
     <div class="texto-reserva">
         <p>Hacer pagos de dividendo, multa, reserva u otro servicio.
         </p>
     </div>
        <select name="deporte">
            <option>dividendo</option>
            <option>multa</option>
            <option>reserva</option>
            <option>contribucion</option>
        </select>
            <br><br>
            {% csrf_token %}
            <div id="paypal-button-container"></div>
        </form>
 </div>
</div>
      <script
      src="https://www.paypal.com/sdk/js?client-id=AQ0y3vHRdaveY0MQP23VNzQx7g0ta4d1ZaNYdgFp3Zdps2DUo_5OjeJYhJAXOasYwhXC5sZ_dkHTDXcM"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
      </script>
      <script>
        paypal.Buttons({
          createOrder: function(data, actions) {
            // This function sets up the details of the transaction, including the amount and line item details.
            return actions.order.create({
              purchase_units: [{
                amount: {
                  value: '0.01'
                }
              }]
            });
          },
          onApprove: function(data) {
            return fetch('/pago/', {
              method:'POST',
              headers: {
                'content-type': 'application/json',
                'X-CSRFToken': csrftoken,
              },
              body: JSON.stringify({
                orderID: data.orderID
              })
            }).then(function(res) {
              return res.json();
            }).then(function(details) {
              alert(' ' + details.mensaje);
            })
           }
        }).render('#paypal-button-container');
        //This function displays Smart Payment Buttons on your web page.
      </script>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/perfil.html
{% extends "cliente_generic.html" %}
{% load static %}


{% block content %}

<center> 
<div class="menu2">
 <ul class="menu2">
     <h2><strong> Datos personales </strong></h2>
     <br>
     <li >
        <h3>Nombre de Usuario</h3>
        <p><a href="#">{{ user.username}}</a></p>
    </li>
    <li >
        <h3>Nombre</h3>
        <p><a href="#">{{ user.cli_Nombre}}</a></p>
    </li>
    <li>
        <h3>Apellido</h3>
        <p><a href="#">{{ user.cli_Apellidos}}</a></p>
    </li>
    <li>
        <h3>Edad</h3>
        <p><a href="#">{{ user.cli_Edad}}</a></p>
    </li>
    <li>
        <h3>Nacionalidad</h3>
        <p><a href="#">{{ user.cli_Nacionalidad}}</a></p>
    </li>
    <li>
        <h3>Email</h3>
        <p><a href="#">{{ user.email}}</a></p>
    </li>
    <li>
        <h3>Rut</h3>
        <p><a href="#">{{ user.cli_Rut}}</a></p>
    </li>

    <li>
        <h3>Telefono</h3>
        <p><a href="#">{{ user.cli_Telefono}}</a></p>
    </li>

    <li>
        <div class="botones-perfil">
        <h3>Cambiar mi contraseña</h3>
        <a href="/update">Cambiar</a>
        </div>
    </li>
    <li>
        <div class="botones-perfil">
        <h3>Añadir Acompañantes a tu lista</h3>
        <a href="/registroacom">Añadir Acompañante</a>
        </div>
    </li>
    <li>
        <div class="botones-perfil">
        <h3>Ver a mis acompañantes</h3>
        <a href="/lista_acompañante">Mis Acompañante</a>
        </div>
    </li>
</div>
</center>


{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/perfil_funcionario.html
{% extends "cliente_generic.html" %}
{% load static %}

{% block content %}

<center> 
<div class="menu2">
 <ul class="menu2">
     <h2><strong> Datos personales </strong></h2>
     <br>
    <li >
        <h3>Correo</h3>
        <p><a href="#">{{ user.email}}</a></p>
    </li>
    <li >
        <h3>Nombre</h3>
        <p><a href="#">{{ user.cli_Nombre}}</a></p>
    </li>
    <li>
        <h3>Apellido</h3>
        <p><a href="#">{{ user.cli_Apellidos}}</a></p>
    </li>
    <li>
        <h3>Edad</h3>
        <p><a href="#">{{ user.cli_Edad}}</a></p>
    </li>
    <li>
        <h3>Nacionalidad</h3>
        <p><a href="#">{{ user.cli_Nacionalidad}}</a></p>
    </li>
    <li>
        <h3>Rut</h3>
        <p><a href="#">{{ user.cli_Rut}}</a></p>
    </li>

    <li>
        <h3>Telefono</h3>
        <p><a href="#">{{ user.cli_Telefono}}</a></p>
    </li>
</div>
</center>

{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/reserva.html
{% extends "cliente_generic.html" %}
{% load static %}

{% block content %}
<div class="listadoreserva">
  <div class="container">
      <h1>Departamentos</h1>
      <div style="height:50px"></div>
      <p class="lead">
      <hr>
      <table class="table table-bordered order-table ">
        <thead>
        <div class="nombrestr">
          <tr>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Valor diario</th>
            <th>Disponibilidad</th>
            <th>Comuna</th>
          </tr>
        </thead>
      </div>
      {% for departamento in departamento %}
        <tr>
          <td>{{ departamento.Codigo}}</td>
          <td>{{ departamento.Nombre_Departamento}}</td>
          <td>{{ departamento.Valor_Diario}}</td>
          <td>{{ departamento.Disponible}}</td>
          <td>{{ departamento.comuna}}</td>
          </tr>
      {% endfor %}
      </table>
      </div>
  </div>

<div class="reserva-arriendo">
  <div class="contenedor">
      <form action="" class="form" method="POST">
      <div class="form-header">
          <h1 class="form-title"><i class="fas fa-plus-circle"></i>Reserva<span> Departamento </span></h1>
      </div> 
               <label>Codigo de departamento deseado</label><br>
               {{ form.Codigo }}<hr><br>
               <label>Cantidad de dias</label><br>
               {{ form.count }}<hr><br>
               <label>Cantidad de dias</label><br>
               {{ form.Fecha_Reserva_Inicios }}<hr><br>
               <label>Cantidad de dias</label><br>
               {{ form.Fecha_Reserva_Terminos }}<hr><br>
               <label>Servicios</label><br>
               {{ form.servicioextra }}<hr><br>
               {% if user is request.user %}
               {{ form.user }}<hr><br>
               {% endif %}
               <br><br>
               {% csrf_token %}
               <input type="submit" class="form-submit" value="Reservar">
               <input type="reset" class="form-submit" value="Limpiar Formulario">
               <a href="/inicio">Volver al Menu</a>
        </form>
  </div>
</div>
{% endblock %}

Portafolio 2.0/portafolio/aplicacion/templates/update.html
{% extends "cliente_generic.html" %}
{% load static %}


{% block content %}
  <div class="reserva-arriendo">
    <div class="contenedor">
        <form action="" class="form" method="POST">
        <div class="form-header">
            <h1 class="form-title"><i class="fas fa-plus-circle"></i>Cambiar <span> Contraseña </span></h1>
        </div> 
        <div class="texto-reserva">
            <p>Actualizacion de contraseña de: {{ user.username }}.
            </p>
        </div>
              <label>Contrasñea Actual</label><br>
              <input type="password" class="form-control" name="password1" placeholder="contraseña actual">
              <label>Nueva Contraseña</label><br>
              <input type="password" class="form-control" name="password2" placeholder="nueva contraseña">
              <br><br>
                 {% csrf_token %}
                 <input class="btn btn-lg btn-primary btn-block" type="submit" value="Actualizar Contraseña">
                </form>
             </div>
         </div>
{% endblock %}